name: Deploy to Azure Web App (dev)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  APP_NAME: angelgoddsantana-me

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Pull Git LFS assets
        run: |
          git lfs install
          git lfs pull

      - name: Build Vite app
        run: pnpm build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Create deployment package
        run: |
          zip -r deploy.zip . \
            -x "*.git*" "node_modules/*" "**/.vite/**" \
               "package.json" "pnpm-lock.yaml"

      - name: Compose Kudu endpoint
        id: kudu
        env:
          PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        shell: bash
        run: |
          set -euo pipefail
          XML="$PUBLISH_PROFILE"
          URL=$(printf "%s" "$XML" | tr '\n' ' ' | sed -n 's/.*publishUrl="\([^"]*\)".*/\1/p' | head -n1)
          if [ -z "$URL" ]; then echo "Failed to find publishUrl in profile" >&2; exit 1; fi
          case "$URL" in http* ) : ;; * ) URL="https://$URL" ;; esac
          echo "KUDU_URL=$URL" >> "$GITHUB_OUTPUT"

      - name: Deploy via Kudu Zip Deploy
        shell: bash
        env:
          KUDU_USER: ${{ secrets.AZURE_WEBAPP_PUBLISH_USERNAME }}
          KUDU_PWD: ${{ secrets.AZURE_WEBAPP_PUBLISH_PASSWORD }}
        run: |
          set -euo pipefail
          echo "::add-mask::$KUDU_USER"
          echo "::add-mask::$KUDU_PWD"
          KUDU_API="${{ steps.kudu.outputs.KUDU_URL }}"/api/zipdeploy?isAsync=true
          curl -sS -u "$KUDU_USER:$KUDU_PWD" -H "Content-Type: application/zip" \
            --data-binary @deploy.zip "$KUDU_API"
